### PR TITLE
W/l icons

### PR DESCRIPTION
**Pull request by bnmajor**
Adds icons needed for the window/level support we're adding: a reset icon and an icon for toggling on/off the feature.

Also considered [this](https://icon-sets.iconify.design/material-symbols/reset-image/) as an alternative to the reset icon added here. Open to suggestions to change either icon!

### CODE REVIEW

**Comment by bnmajor** [comment]
@thewtex

**Comment by thewtex** [comment]
@bnmajor awesome, thank you!

> Also considered this as an alternative

I love this -- can we use it instead?

**Comment by bnmajor** [comment]
@thewtex Sure thing! Updated to use the reset image icon instead

**Review by thewtex — APPROVED** [review]
:1st_place_medal:

**Pull request merged**
